FROM node:20-alpine AS builder
WORKDIR /E:\workspace\browser_procla
COPY frontend/package*.json ./frontend/
RUN cd frontend- && npm install
COPY frontend- ./frontend
RUN cd frontend- && npm run build
FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /frontend/dist ./dist
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
