services:
  app:
    build:
      context: .
      dockerfile: browser_procla/Dockerfile
    container_name: browser_procla
    environment:
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
    restart: unless-stopped
    networks:
      - app-network

  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge